# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - usf_arm_controller

  usf_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - link0_to_base_link
      - link1_to_link0
      - link2_to_link1
      - wrist_to_link2
      - claw0_to_wrist
    action_ns: follow_joint_trajectory
    default: true