# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    usf_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

usf_arm_controller:
  ros__parameters:
    joints:
      - link0_to_base_link
      - link1_to_link0
      - link2_to_link1
      - wrist_to_link2
      - claw0_to_wrist
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity